Added ability to show all core temperatures in status line at once.
HarlemSquirrel/gnome-shell-extension-sensory-perception pull request #1
Opened 2017-07-15 14:59 UTC by NickOrr0617

Also added a check on the core temperatures against the "high" temperature
from sensors and prepending an exclamation point if the temperature of the
core exceeds that value.  This gives a visual warning to the user
that the cores may be overheating.

2017-07-17 13:28 UTC, HarlemSquirrel requested changes

2017-07-17 13:28 UTC, HarlemSquirrel commented on extension.js
> +            //this.statusLabel.set_text(allCoreTemps);
Did you want this line in here?

2017-07-18 04:48 UTC, NickOrr0617 commented on extension.js
> +            //this.statusLabel.set_text(allCoreTemps);
Doesn't need to be, that was my first crack at it, before I decided to make it configurable I just hacked all the cores in for my personal usage.

2017-07-18 13:53 UTC, HarlemSquirrel commented on extension.js
> +            //this.statusLabel.set_text(allCoreTemps);
OK, it looks good! Could you please remove this comment?

2017-07-18 15:54 UTC, NickOrr0617 commented
Changes made!

2017-07-18 18:35 UTC, HarlemSquirrel approved these changes

2017-07-18 18:35 UTC, merged